name: Terraform CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform Checks'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout GitHub repository'
        uses: actions/checkout@v3

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: 'Terraform Init'
        run: terraform init

      - name: 'Terraform Format Check'
        run: terraform fmt -check

      - name: 'Terraform Validate'
        run: terraform validate

      - name: 'Terraform Plan'
        run: terraform plan
